version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=cargodb_new
      - POSTGRES_USER=shahan01
      - POSTGRES_PASSWORD=543212345
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis:alpine
  celery:
    build: .
    command: celery -A Cargo worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    command: celery -A Cargo beat -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

volumes:
  postgres_data:

# root@76b973b41d44:/# psql -U shahan -d cargodb