# Generated by Django 3.2 on 2023-03-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('sign', models.CharField(max_length=1)),
                ('rate', models.FloatField()),
            ],
        ),
    ]
