# Generated by Django 3.2 on 2023-03-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_auto_20230319_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneprefix',
            name='prefix',
            field=models.CharField(default=2, max_length=6),
            preserve_default=False,
        ),
    ]
