# Generated by Django 3.2 on 2023-03-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230319_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='name',
            field=models.CharField(default=2, max_length=32),
            preserve_default=False,
        ),
    ]
