# Generated by Django 3.2 on 2023-03-23 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_warehouse_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
