# Generated by Django 3.2 on 2023-03-27 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.DeleteModel(
            name='SingletonModel',
        ),
    ]
