# Generated by Django 3.2 on 2023-04-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constant_or_percentage', models.IntegerField(choices=[(1, 'Constant'), (0, 'Percentage')], default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('reason', models.CharField(choices=[('Female', 'Female'), ('Young', 'Young'), ('Superuser', 'Superuser')], max_length=32)),
            ],
        ),
    ]
