# Generated by Django 3.2 on 2023-04-01 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('max_weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fixed_or_per_gram', models.IntegerField(choices=[(1, 'Fixed'), (2, 'Per Gram')], default=2)),
                ('is_liquid', models.IntegerField(choices=[(1, 'Liquid'), (0, 'Not Liquid')], default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='core.country')),
            ],
        ),
    ]
