# Generated by Django 3.2 on 2023-04-03 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20230403_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttype',
            old_name='type',
            new_name='parent_type',
        ),
    ]
