# Generated by Django 3.2 on 2023-04-04 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_faq_answer'),
        ('core', '0014_auto_20230402_2017'),
        ('core', '0014_auto_20230403_1021'),
    ]

    operations = [
    ]
