# Generated by Django 3.2 on 2023-04-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_20230404_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
