# Generated by Django 3.2 on 2023-04-21 08:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_faq_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('airwaybill_address', models.CharField(max_length=32)),
                ('address_header', models.CharField(max_length=32)),
                ('client_code', models.CharField(default='C.code', max_length=8)),
                ('name_surname', models.CharField(default="User's name and surname", max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('flexible_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('address_for_user', models.CharField(blank=True, max_length=256, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country')),
            ],
        ),
    ]
