# Generated by Django 3.2 on 2023-04-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_foreignwarehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignwarehouse',
            name='flexible_data',
            field=models.JSONField(),
        ),
    ]
