# Generated by Django 3.2 on 2023-04-28 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_currency_rate'),
        ('core', '0018_delete_warehouse'),
    ]

    operations = [
    ]
