# Generated by Django 3.2 on 2023-05-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_foreignwarehouse_flexible_data'),
        ('core', '0019_merge_0017_alter_currency_rate_0018_delete_warehouse'),
    ]

    operations = [
    ]
