# Generated by Django 3.2 on 2023-05-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20230503_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignwarehouse',
            name='client_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='foreignwarehouse',
            name='name_surname',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
