# Generated by Django 3.2 on 2023-05-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20230504_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='max_weight',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='min_weight',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
