# Generated by Django 3.2 on 2023-03-28 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20230326_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fin_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9A-Za-z]{7}$', message='Fin Code has to be 7 characters with letters and digits')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gov_id',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gov_prefix',
            field=models.CharField(blank=True, choices=[('AZE', 'AZE'), ('AA', 'AA'), ('MYI', 'MYI'), ('DYI', 'DYI')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{7}$', message='Please enter your valid phone number')]),
        ),
    ]
