# Generated by Django 3.2 on 2023-03-28 08:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_fin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='client_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fin_code',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^[0-9A-Za-z]{7}$', message='Fin Code has to be 7 characters with letters and digits')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='gov_id',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator('^\\d{7}$', message='Please enter your valid phone number')]),
        ),
    ]
