# Generated by Django 3.2 on 2023-03-28 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20230328_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='client_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fin_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9A-Za-z]{7}$', message='Fin Code has to be 7 characters with letters and digits')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='gov_id',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^\\d{7}$', message='Please enter your valid phone number')]),
        ),
    ]
