# Generated by Django 3.2 on 2023-05-03 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20230428_2039'),
        ('order', '0002_statushistory'),
    ]

    operations = [
    ]
