# Generated by Django 3.2 on 2023-05-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_merge_0002_auto_20230428_2039_0002_statushistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statushistory',
            name='new_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='old_status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
