# Generated by Django 3.2 on 2023-05-07 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20230503_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statushistory',
            name='new_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_statuses', to='order.statushistory'),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='old_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_statuses', to='order.statushistory'),
        ),
    ]
