# Generated by Django 3.2 on 2023-05-07 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20230507_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statushistory',
            name='new_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_statuses', to='order.status'),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='old_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_statuses', to='order.status'),
        ),
    ]
