# Generated by Django 3.2 on 2023-05-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20230508_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='declaration',
            old_name='discount',
            new_name='discounts',
        ),
    ]
